"use client"

import { useState } from "react"
import { Download, Copy, Share2, ArrowLeft, Globe } from "lucide-react"
import Link from "next/link"

const FULL_MARKDOWN = `# DESIGN.md — stripe.com

Generated by DESIGN.MD on ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}

---

## 1. Overview

Stripe's visual identity communicates trust, precision, and technical sophistication. The design language is clean and confident — enterprise-grade without being sterile. A dark-on-light base with a signature indigo-violet accent creates a memorable brand fingerprint that scales from marketing to product UI.

**Design Principles:** Precision over decoration. Information density without clutter. Every element earns its place.

---

## 2. Color Tokens

### Brand Colors
| Token | Value | Usage |
|-------|-------|-------|
| \`--color-brand\` | \`#635BFF\` | Primary brand, CTAs, links |
| \`--color-brand-dark\` | \`#4F46E5\` | Hover states, pressed |
| \`--color-brand-light\` | \`#7C74FF\` | Subtle highlights |

### Semantic Colors
| Token | Value | Usage |
|-------|-------|-------|
| \`--color-success\` | \`#09A660\` | Positive states, confirmations |
| \`--color-warning\` | \`#E5A03C\` | Caution states |
| \`--color-error\` | \`#DF1B41\` | Error states, destructive actions |
| \`--color-info\` | \`#3B6FEB\` | Informational messages |

### Neutral Scale
| Token | Value | Usage |
|-------|-------|-------|
| \`--color-text-primary\` | \`#0A2540\` | Headings, body copy |
| \`--color-text-secondary\` | \`#425466\` | Subheadings, secondary text |
| \`--color-text-muted\` | \`#8898AA\` | Labels, metadata, captions |
| \`--color-surface\` | \`#FFFFFF\` | Page backgrounds |
| \`--color-surface-subtle\` | \`#F6F9FC\` | Card backgrounds, sections |
| \`--color-surface-raised\` | \`#EDF2F7\` | Elevated surfaces |
| \`--color-border\` | \`#E0E7F0\` | Dividers, outlines |
| \`--color-border-strong\` | \`#C1CDD9\` | Emphasized borders |

---

## 3. Typography

**Primary Font Stack:** \`"Sohne", "Helvetica Neue", system-ui, sans-serif\`
**Code Font Stack:** \`"Roboto Mono", "Courier New", monospace\`

### Type Scale
| Name | Size | Weight | Line Height | Letter Spacing | Usage |
|------|------|--------|-------------|----------------|-------|
| Display XL | 72px | 700 | 1.08 | -0.02em | Hero headlines |
| Display L | 56px | 700 | 1.1 | -0.02em | Section heroes |
| Display M | 40px | 700 | 1.15 | -0.01em | Feature headers |
| Heading XL | 32px | 600 | 1.25 | 0 | Section titles |
| Heading L | 24px | 600 | 1.3 | 0 | Subsection titles |
| Heading M | 20px | 600 | 1.35 | 0 | Card headers |
| Body XL | 20px | 400 | 1.6 | 0 | Intro paragraphs |
| Body L | 18px | 400 | 1.65 | 0 | Feature descriptions |
| Body | 16px | 400 | 1.65 | 0 | Default body copy |
| Small | 14px | 400 | 1.5 | 0 | Labels, secondary |
| XSmall | 12px | 400 | 1.4 | 0.02em | Captions, metadata |

### Typography Rules
- Never exceed 68 characters per line for body text
- Use semibold (600) for interactive labels, not bold (700)
- Headlines above 40px: always -0.02em letter spacing
- Code blocks: always 14px Roboto Mono

---

## 4. Spacing & Layout

### Spacing Scale (4px base)
\`4px · 8px · 12px · 16px · 20px · 24px · 32px · 40px · 48px · 64px · 80px · 96px · 128px\`

### Grid System
- **Max content width:** 1200px
- **Column gutter:** 24px
- **Outer margin:** 40px (desktop), 24px (tablet), 16px (mobile)
- **Columns:** 12 (desktop), 8 (tablet), 4 (mobile)

### Breakpoints
| Name | Width | Usage |
|------|-------|-------|
| Mobile | < 480px | Single column |
| Tablet | 480–1024px | 2-column grid |
| Desktop | > 1024px | Full 12-col grid |
| Wide | > 1440px | Constrained to 1200px max |

### Border Radius
| Token | Value | Usage |
|-------|-------|-------|
| \`--radius-sm\` | \`4px\` | Buttons, badges |
| \`--radius-md\` | \`8px\` | Cards, inputs |
| \`--radius-lg\` | \`12px\` | Modals, panels |
| \`--radius-full\` | \`9999px\` | Pills, avatars |

---

## 5. Shadows & Elevation

| Token | Value | Usage |
|-------|-------|-------|
| \`--shadow-xs\` | \`0 1px 2px rgba(10,37,64,0.06)\` | Subtle, inline elements |
| \`--shadow-sm\` | \`0 2px 8px rgba(10,37,64,0.08), 0 1px 2px rgba(10,37,64,0.04)\` | Cards at rest |
| \`--shadow-md\` | \`0 4px 16px rgba(10,37,64,0.1), 0 2px 4px rgba(10,37,64,0.06)\` | Hovering cards, dropdowns |
| \`--shadow-lg\` | \`0 12px 40px rgba(10,37,64,0.14), 0 4px 12px rgba(10,37,64,0.08)\` | Modals, popovers |
| \`--shadow-brand\` | \`0 4px 16px rgba(99,91,255,0.3)\` | Brand CTA buttons |

---

## 6. Component Patterns

### Buttons
\`\`\`css
/* Primary */
.btn-primary {
  background: #635BFF;
  color: white;
  padding: 10px 20px;
  border-radius: 6px;
  font-size: 15px;
  font-weight: 600;
  transition: background 150ms, box-shadow 150ms, transform 100ms;
}
.btn-primary:hover {
  background: #4F46E5;
  box-shadow: var(--shadow-brand);
  transform: translateY(-1px);
}

/* Secondary (ghost) */
.btn-secondary {
  background: transparent;
  color: #425466;
  border: 1.5px solid #C1CDD9;
  padding: 10px 20px;
  border-radius: 6px;
}
\`\`\`

### Cards
\`\`\`css
.card {
  background: white;
  border: 1px solid #E0E7F0;
  border-radius: 12px;
  padding: 24px;
  box-shadow: var(--shadow-sm);
  transition: box-shadow 200ms, transform 200ms;
}
.card:hover {
  box-shadow: var(--shadow-md);
  transform: translateY(-2px);
}
\`\`\`

---

## 7. Animation & Motion

### Easing Curves
| Token | Value | Usage |
|-------|-------|-------|
| \`--ease-default\` | \`cubic-bezier(0.4, 0, 0.2, 1)\` | Most transitions |
| \`--ease-in\` | \`cubic-bezier(0.4, 0, 1, 1)\` | Exits, hiding |
| \`--ease-out\` | \`cubic-bezier(0, 0, 0.2, 1)\` | Entrances, reveals |
| \`--ease-spring\` | \`cubic-bezier(0.175, 0.885, 0.32, 1.275)\` | Micro-interactions |

### Duration Scale
\`50ms · 100ms · 150ms · 200ms · 300ms · 500ms · 700ms · 1000ms\`

### Motion Principles
- Hover transitions: 150–200ms
- Page transitions: 300–400ms
- Content reveals: stagger 50ms per element
- Never animate properties that cause layout recalculation

---

## 8. Brand Voice in Design

**Tone:** Confident but not arrogant. Technical but approachable. Dense but scannable.

**Visual cues that reinforce voice:**
- Monospaced type for code and numbers — precision and technical credibility
- High-contrast text ratios — clarity and accessibility as brand values
- Conservative animation — competence over flair
- Dense information layouts — respect for the user's intelligence
- Consistent 4px grid — systematic thinking made visible`

const CSS_VARIABLES = `/* DESIGN.md — stripe.com — CSS Variables */
/* Generated by DESIGN.MD */

:root {
  /* Brand */
  --color-brand: #635BFF;
  --color-brand-dark: #4F46E5;
  --color-brand-light: #7C74FF;

  /* Semantic */
  --color-success: #09A660;
  --color-warning: #E5A03C;
  --color-error: #DF1B41;
  --color-info: #3B6FEB;

  /* Neutral */
  --color-text-primary: #0A2540;
  --color-text-secondary: #425466;
  --color-text-muted: #8898AA;
  --color-surface: #FFFFFF;
  --color-surface-subtle: #F6F9FC;
  --color-surface-raised: #EDF2F7;
  --color-border: #E0E7F0;
  --color-border-strong: #C1CDD9;

  /* Typography */
  --font-sans: "Sohne", "Helvetica Neue", system-ui, sans-serif;
  --font-mono: "Roboto Mono", "Courier New", monospace;

  /* Spacing */
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 12px;
  --space-4: 16px;
  --space-5: 20px;
  --space-6: 24px;
  --space-8: 32px;
  --space-10: 40px;
  --space-12: 48px;
  --space-16: 64px;
  --space-20: 80px;

  /* Border Radius */
  --radius-sm: 4px;
  --radius-md: 8px;
  --radius-lg: 12px;
  --radius-full: 9999px;

  /* Shadows */
  --shadow-xs: 0 1px 2px rgba(10,37,64,0.06);
  --shadow-sm: 0 2px 8px rgba(10,37,64,0.08), 0 1px 2px rgba(10,37,64,0.04);
  --shadow-md: 0 4px 16px rgba(10,37,64,0.10), 0 2px 4px rgba(10,37,64,0.06);
  --shadow-lg: 0 12px 40px rgba(10,37,64,0.14), 0 4px 12px rgba(10,37,64,0.08);
  --shadow-brand: 0 4px 16px rgba(99,91,255,0.30);

  /* Animation */
  --ease-default: cubic-bezier(0.4, 0, 0.2, 1);
  --ease-in: cubic-bezier(0.4, 0, 1, 1);
  --ease-out: cubic-bezier(0, 0, 0.2, 1);
  --ease-spring: cubic-bezier(0.175, 0.885, 0.32, 1.275);
  --duration-fast: 150ms;
  --duration-base: 200ms;
  --duration-slow: 300ms;
}`

const TAILWIND_CONFIG = `/** @type {import('tailwindcss').Config} */
/* DESIGN.md — stripe.com — Tailwind Config */
/* Generated by DESIGN.MD */

module.exports = {
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: '#635BFF',
          dark: '#4F46E5',
          light: '#7C74FF',
        },
        surface: {
          DEFAULT: '#FFFFFF',
          subtle: '#F6F9FC',
          raised: '#EDF2F7',
        },
        text: {
          primary: '#0A2540',
          secondary: '#425466',
          muted: '#8898AA',
        },
        border: {
          DEFAULT: '#E0E7F0',
          strong: '#C1CDD9',
        },
        success: '#09A660',
        warning: '#E5A03C',
        error: '#DF1B41',
        info: '#3B6FEB',
      },
      fontFamily: {
        sans: ['"Sohne"', '"Helvetica Neue"', 'system-ui', 'sans-serif'],
        mono: ['"Roboto Mono"', '"Courier New"', 'monospace'],
      },
      fontSize: {
        'display-xl': ['72px', { lineHeight: '1.08', letterSpacing: '-0.02em' }],
        'display-l': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-m': ['40px', { lineHeight: '1.15', letterSpacing: '-0.01em' }],
        'heading-xl': ['32px', { lineHeight: '1.25' }],
        'heading-l': ['24px', { lineHeight: '1.3' }],
        'heading-m': ['20px', { lineHeight: '1.35' }],
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(10,37,64,0.06)',
        sm: '0 2px 8px rgba(10,37,64,0.08), 0 1px 2px rgba(10,37,64,0.04)',
        md: '0 4px 16px rgba(10,37,64,0.10), 0 2px 4px rgba(10,37,64,0.06)',
        lg: '0 12px 40px rgba(10,37,64,0.14), 0 4px 12px rgba(10,37,64,0.08)',
        brand: '0 4px 16px rgba(99,91,255,0.30)',
      },
      transitionTimingFunction: {
        default: 'cubic-bezier(0.4, 0, 0.2, 1)',
        spring: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      },
    },
  },
}`

const JSON_TOKENS = JSON.stringify({
  color: {
    brand: { value: "#635BFF", type: "color" },
    "brand-dark": { value: "#4F46E5", type: "color" },
    "brand-light": { value: "#7C74FF", type: "color" },
    "text-primary": { value: "#0A2540", type: "color" },
    "text-secondary": { value: "#425466", type: "color" },
    "text-muted": { value: "#8898AA", type: "color" },
    surface: { value: "#FFFFFF", type: "color" },
    "surface-subtle": { value: "#F6F9FC", type: "color" },
    border: { value: "#E0E7F0", type: "color" },
    success: { value: "#09A660", type: "color" },
    warning: { value: "#E5A03C", type: "color" },
    error: { value: "#DF1B41", type: "color" },
  },
  typography: {
    "font-sans": { value: "Sohne, Helvetica Neue, system-ui, sans-serif", type: "fontFamily" },
    "font-mono": { value: "Roboto Mono, Courier New, monospace", type: "fontFamily" },
  },
  spacing: {
    "1": { value: "4px", type: "spacing" },
    "2": { value: "8px", type: "spacing" },
    "4": { value: "16px", type: "spacing" },
    "6": { value: "24px", type: "spacing" },
    "8": { value: "32px", type: "spacing" },
  },
}, null, 2)

const TABS = ["Markdown", "CSS Variables", "Tailwind Config", "JSON Tokens"] as const
type Tab = typeof TABS[number]

const TAB_CONTENT: Record<Tab, string> = {
  "Markdown": FULL_MARKDOWN,
  "CSS Variables": CSS_VARIABLES,
  "Tailwind Config": TAILWIND_CONFIG,
  "JSON Tokens": JSON_TOKENS,
}

function renderMarkdown(text: string) {
  const lines = text.split("\n")
  return lines.map((line, i) => {
    if (line.startsWith("# ")) return <div key={i} className="syntax-h1 mb-2">{line.slice(2)}</div>
    if (line.startsWith("## ")) return <div key={i} className="syntax-h2 mt-5 mb-2">{line.slice(3)}</div>
    if (line.startsWith("### ")) return <div key={i} className="syntax-h3 mt-4 mb-1">{line.slice(4)}</div>
    if (line.startsWith("---")) return <hr key={i} className="border-border my-4" />
    if (line.startsWith("| ")) return <div key={i} className="syntax-table text-[#F0EDE4]/70">{line}</div>
    if (line.startsWith("```")) return <div key={i} className="text-[#C084FC] text-xs font-mono">{line}</div>
    if (line.match(/`[^`]+`/)) {
      const parts = line.split(/(`[^`]+`)/)
      return (
        <div key={i} className="syntax-text">
          {parts.map((part, j) =>
            part.startsWith("`") && part.endsWith("`")
              ? <code key={j} className="syntax-code bg-[#1a1a18] px-1 rounded">{part.slice(1, -1)}</code>
              : part
          )}
        </div>
      )
    }
    if (line.startsWith("**") && line.endsWith("**")) return <div key={i} className="syntax-text font-semibold">{line.slice(2, -2)}</div>
    if (line === "") return <div key={i} className="h-1.5" />
    return <div key={i} className="syntax-text">{line}</div>
  })
}

export default function ResultPage() {
  const [activeTab, setActiveTab] = useState<Tab>("Markdown")
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(TAB_CONTENT[activeTab])
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const ext = activeTab === "Markdown" ? "md" : activeTab === "CSS Variables" ? "css" : activeTab === "Tailwind Config" ? "js" : "json"
    const blob = new Blob([TAB_CONTENT[activeTab]], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `DESIGN.${ext}`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const isCode = activeTab !== "Markdown"

  return (
    <div className="min-h-screen flex flex-col">
      {/* Top bar */}
      <header className="border-b border-border bg-surface px-6 py-4 flex items-center justify-between gap-4 flex-wrap">
        <div className="flex items-center gap-4">
          <Link
            href="/dashboard"
            className="flex items-center gap-1.5 text-xs text-muted hover:text-foreground transition-colors font-mono"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Dashboard
          </Link>
          <div className="w-px h-4 bg-border" />
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 rounded bg-[#1a1a18] border border-border flex items-center justify-center overflow-hidden">
              <Globe className="w-3 h-3 text-muted" strokeWidth={1.5} />
            </div>
            <span className="text-sm font-mono text-foreground font-medium">stripe.com</span>
            <span className="text-xs text-muted font-mono">
              · {new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleShare}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-muted hover:text-foreground border border-border hover:border-[#444442] rounded transition-all font-mono"
          >
            <Share2 className="w-3 h-3" />
            {copied ? "Copied!" : "Share"}
          </button>
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-muted hover:text-foreground border border-border hover:border-[#444442] rounded transition-all font-mono"
          >
            <Copy className="w-3 h-3" />
            Copy
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium bg-accent text-[#0A0A08] rounded hover:bg-accent-muted transition-all duration-150 font-mono"
          >
            <Download className="w-3 h-3" />
            Download
          </button>
        </div>
      </header>

      {/* Split view */}
      <div className="flex flex-1 min-h-0">
        {/* Left: rendered preview */}
        <div className="flex-1 overflow-y-auto border-r border-border p-8">
          <div className="max-w-2xl mx-auto">
            {/* macOS window chrome */}
            <div className="flex items-center gap-2 px-4 py-3 bg-[#0d0d0b] rounded-t-lg border border-border border-b-0">
              <span className="w-3 h-3 rounded-full mac-dot-red" />
              <span className="w-3 h-3 rounded-full mac-dot-yellow" />
              <span className="w-3 h-3 rounded-full mac-dot-green" />
              <span className="ml-3 text-xs text-muted font-mono flex-1 text-center">
                DESIGN.md — stripe.com
              </span>
            </div>
            <div className="bg-surface border border-border border-t-0 rounded-b-lg p-6">
              {renderMarkdown(FULL_MARKDOWN)}
            </div>
          </div>
        </div>

        {/* Right: export formats */}
        <div className="w-[480px] flex-shrink-0 flex flex-col">
          {/* Tabs */}
          <div className="flex border-b border-border bg-surface overflow-x-auto">
            {TABS.map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-4 py-3 text-xs font-mono whitespace-nowrap transition-all border-b-2 -mb-px ${
                  activeTab === tab
                    ? "text-accent border-accent"
                    : "text-muted border-transparent hover:text-foreground"
                }`}
              >
                {tab}
              </button>
            ))}
          </div>

          {/* Code panel */}
          <div className="flex-1 overflow-y-auto p-4 bg-[#0d0d0b]">
            <pre
              className={`text-xs leading-relaxed whitespace-pre-wrap ${
                isCode ? "text-[#E0E0DC] font-mono" : ""
              }`}
            >
              {isCode ? TAB_CONTENT[activeTab] : (
                <div>{renderMarkdown(TAB_CONTENT[activeTab])}</div>
              )}
            </pre>
          </div>
        </div>
      </div>
    </div>
  )
}
